steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-f'
      - 'apps/api/Dockerfile'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/sigweb/api:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/sigweb/api:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sigweb-api-dev
      - '--image=us-east1-docker.pkg.dev/$PROJECT_ID/sigweb/api:latest'
      - '--region=us-east1'
      - '--project=$PROJECT_ID'
      - '--quiet'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/sigweb/api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
